### ISSUE TITLE
Password reset not working for us

### ISSUE THREAD

**Issue by samuk** [njsubedi/cloudron-keycloak#3]
I correctly recieve the email but when clicking the link I get a message ''your account has been updated' but this does not enable me to choose a new password

**Comment by njsubedi** [comment]
I’ll follow up on this; thanks for reporting.

**Comment by marc-farre** [comment]
I think this we could close this issue as the problem was custom settings in "Authentification" -> "Required actions": "Update password" must stay checked, as it is the case on fresh Keycloak installation.

**Comment by samuk** [comment]
@funkycram Thanks, this does resolve the issue
