### ISSUE TITLE
Email default settings are restored each time the container is restarted

### ISSUE THREAD

**Issue by marc-farre** [njsubedi/cloudron-keycloak#4]
We have 2 problems with emails sending:
- the default settings does not work (emails cannot be sent), but maybe it's a specific problem to our network.
- when the emails settings are customized, in "Realm settings" -> "Email", each time the container is restarted, the default settings are restored.

**Comment by njsubedi** [comment]
This is an expected behavior because one can change the app settings to give it a different email. You can change the email address  from the Cloudron dashboard.

**Comment by marc-farre** [comment]
Well, even changing the email gives the "Failed to send email" error.

For example, with default settings, I have:
- Host: mail
- Port: 2525
- Enable StartTLS: off

If I change the following fields with:
- Host: my.cloudron-domain.tdl
- Port: 587
- Enable StartTLS: on

Email sending works.
What's strange is that the same default configuration (Host: mail, Port: 2525) works on others apps (e.g. Nextcloud).

But beside this problem, I think we should be able to change the email settings if we want to use an email other than Cloudron, e.g. transactional emails.

Thanks!

**Comment by marc-farre** [comment]
Hi @njsubedi,
We are still facing this problem.
Would there be a solution to keep the emails settings after the container is restarted?
Thanks!

**Comment by samuk** [comment]
@njsubedi do you have any update on this?

**Comment by njsubedi** [comment]
> Would there be a solution to keep the emails settings after the container is restarted?

Please set the email configuration from the Cloudron dashboard instead of changing them inside the Keycloak realm setting. Every time the container is restarted, it replaces the values in the existing email settings with the values provided by Cloudron environment.

**Comment by marc-farre** [comment]
Hi @njsubedi we finally managed to make Keycloak send email with the default settings (Host: mail | Port: 2525).
The problem was that there is a space char at the end of the username, as you can see here (in gray):
![image](https://user-images.githubusercontent.com/23310825/207837535-1ceadb4a-0d29-4986-85ca-1c268705fa6a.png)

If we remove the space, email sending works. But each time the container restarts, this space is back and emails are not sent.
Could you do something about it?
Thanks very much!

**Comment by marc-farre** [comment]
@njsubedi this should fix the bug: https://github.com/njsubedi/cloudron-keycloak/pull/6
Thanks

**Comment by marc-farre** [comment]
@njsubedi  Thanks for the merge. Is it possible to create a new version with this fix? This will allow us to avoid having emails delivery disruption each time the container is restarted. Thanks!

**Comment by njsubedi** [comment]
It would be best to add a clause in `start.sh` to check for environment variable like “KEEP_SMTP_SETTINGS” and not replace the values. For that to work Cloudron must allow settings runtime environment variables somewhere. I’ll see what can be done.

**Comment by marc-farre** [comment]
Do you think it would be possible to create a version with the bug fixed while waiting to manage the `KEEP_SMTP_SETTINGS` variable? Thanks !

**Comment by njsubedi** [comment]
I’ve already fixed the bug and updated Keycloak version. Since you’re already using the source code and the app isn’t available at the app store, you can simply comment the code and run cloudron build and cloudron install. I’m still trying to figure out a way to do it the cloudron way.
