### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by marc-farre** [njsubedi/cloudron-keycloak#5]
This is not an issue (I think so), but If you have any advice it will help us a lot, thank you in advance!

I created a test theme in the path `/app/data/themes/my-custom-theme` which contains:
- login/theme.properties
- login/resources/css/index.css
- login/resources/js/index.js

The `theme.properties` contains:
```
parent=base
styles=css/index.css
scripts=js/index.js
```

I activated the theme in https://my-keycloak.tdl/admin/master/console/#/realms/cloudron/theme-settings in the login field.
I restarted the container in Cloudron

The CSS and JS are not loaded...
And the same theme works on a Keycloak installed directly on a server of mine (not with Cloudron).

Thanks a lot if you have an idea!

**Comment by samuk** [comment]
@njsubedi Do you have any ideas on this?

List of probably unrelated similar issues 
[Keycloak theme not updating for the realms login from applications](https://stackoverflow.com/questions/65888922/keycloak-theme-not-updating-for-the-realms-login-from-applications) To update the theme of the SSO login page, you need to select the theme using - Realm -> Clients -> Appropriate Client Name -> Theme.

**Comment by njsubedi** [comment]
I’ll look into it. If you can, please post the contents of the theme file, which helps me find an issue quickly because I don’t have any custom themes to check with.

**Comment by marc-farre** [comment]
Thanks a lot @njsubedi .
[keycloak-theme-test.zip](https://github.com/njsubedi/cloudron-keycloak/files/8530682/keycloak-theme-test.zip)

**Comment by samuk** [comment]
I did a post on the [Keycloak forum for this issue](https://keycloak.discourse.group/t/custom-theme-applied-but-does-not-load-cloudron/15094)

**Comment by marc-farre** [comment]
Sorry @njsubedi  actually it works. I got confused in my tests because of the 2 realms... As the default realm is "Cloudron" but when logging in to the admin it is the "Master" realm that is used... So everything is fine Alright now, thank you very much!
